export const allskills = [
    "Python",
    "Java",
    "C++",
    "JavaScript",
    "C#",
    "PHP",
    "Ruby",
    "Go",
    "Swift",
    "Kotlin",
    "HTML",
    "CSS",
    "R",
    "Julia",
    "Java (Android)",
    "Swift/Kotlin (iOS)",
    "React Native (cross-platform)",
    "Python (TensorFlow, PyTorch)",
    "C# (Unity)",
    "C++ (Unreal Engine)",
    "JavaScript",
    "Bash (Linux/macOS)",
    "PowerShell (Windows)",
    "Software development methodologies (Agile, Waterfall)",
    "Version control systems (Git, SVN)",
    "Operating systems (Windows, Linux, macOS)",
    "Cloud computing (AWS, Azure, GCP)",
    "Databases (SQL: MySQL, PostgreSQL, Oracle; NoSQL: MongoDB, Cassandra)",
    "Networking (TCP/IP, OSI model)",
    "Computer architecture",
    "Algorithms and data structures",
    "Security principles",
    "Design patterns",
    "Web development frameworks (React, Angular, Vue.js)",
    "DevOps (CI/CD pipelines)",
    "Testing (unit testing, integration testing)",
    "Debugging skills",
    "Human-computer interaction (HCI)",
    "User interface (UI) and user experience (UX) design",
    "Artificial intelligence (AI)",
    "Machine learning (ML)",
    "Big data processing",
    "Cybersecurity",
    "Blockchain technology",
    "Internet of Things (IoT)",
    "Robotics",
  ];